import { Role } from '@prisma/client';

export const PERMISSIONS = {
  CREATE_PROJECT: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.ADMIN],
  DELETE_PROJECT: [Role.WORKSPACE_OWNER, Role.ADMIN],
  MANAGE_MEMBERS: [Role.WORKSPACE_OWNER, Role.ADMIN],
  CREATE_SPRINT: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.ADMIN],
  ASSIGN_TASK: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.ADMIN],
  UPDATE_TASK_STATUS: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.TEAM_MEMBER, Role.ADMIN],
  DELETE_TASK: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.ADMIN],
  CREATE_COMMENT: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.TEAM_MEMBER, Role.CLIENT, Role.ADMIN],
  VIEW_PROGRESS: [Role.WORKSPACE_OWNER, Role.PROJECT_MANAGER, Role.TEAM_MEMBER, Role.CLIENT, Role.ADMIN],
  MANAGE_SETTINGS: [Role.WORKSPACE_OWNER, Role.ADMIN]
};

export function hasPermission(
  role: Role,
  action: keyof typeof PERMISSIONS
): boolean {
  return (PERMISSIONS[action] as readonly Role[]).includes(role);
}